-- Enable RLS (V7: policies added later; API uses service role which bypasses RLS)

ALTER TABLE users ENABLE ROW LEVEL SECURITY;

ALTER TABLE leagues ENABLE ROW LEVEL SECURITY;

ALTER TABLE league_members ENABLE ROW LEVEL SECURITY;

ALTER TABLE scenarios ENABLE ROW LEVEL SECURITY;

ALTER TABLE scenario_sets ENABLE ROW LEVEL SECURITY;

ALTER TABLE weekly_challenges ENABLE ROW LEVEL SECURITY;

ALTER TABLE challenge_responses ENABLE ROW LEVEL SECURITY;

ALTER TABLE h2h_challenges ENABLE ROW LEVEL SECURITY;

ALTER TABLE weekly_results ENABLE ROW LEVEL SECURITY;

ALTER TABLE sunday_windows ENABLE ROW LEVEL SECURITY;

ALTER TABLE sunday_results ENABLE ROW LEVEL SECURITY;

ALTER TABLE rivalries ENABLE ROW LEVEL SECURITY;

ALTER TABLE season_standings ENABLE ROW LEVEL SECURITY;

ALTER TABLE league_pass_purchases ENABLE ROW LEVEL SECURITY;

ALTER TABLE notifications_log ENABLE ROW LEVEL SECURITY;

ALTER TABLE content_reviews ENABLE ROW LEVEL SECURITY;
